quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=compose-postgres
quarkus.datasource.password=compose-postgres
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/compose-postgres
quarkus.datasource.jdbc.driver=org.postgresql.Driver
quarkus.hibernate-orm.database.default-schema=public
%dev.quarkus.hibernate-orm.database.generation=update

#Devservices to run the database
%dev.quarkus.datasource.devservices.enabled=true
%dev.quarkus.datasource.devservices.image-name=postgres:13.1-alpine
%dev.quarkus.datasource.devservices.username=compose-postgres
%dev.quarkus.datasource.devservices.password=compose-postgres
%dev.quarkus.datasource.devservices.db-name=compose-postgres
%dev.quarkus.datasource.devservices.port=5432
