quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=compose-postgres
quarkus.datasource.password=compose-postgres
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/compose-postgres
quarkus.datasource.jdbc.driver=org.postgresql.Driver
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.database.default-schema=public

#Devservices to run the database
quarkus.datasource.devservices.enabled=true
quarkus.datasource.devservices.image-name=postgres:13.1-alpine
quarkus.datasource.devservices.username=compose-postgres
quarkus.datasource.devservices.password=compose-postgres
quarkus.datasource.devservices.db-name=compose-postgres
quarkus.datasource.devservices.port=5432
